export type GrowthChannel = 'x' | 'linkedin' | 'instagram' | 'facebook' | 'threads' | 'reddit';
export type AttributionModel = 'direct' | 'first_touch' | 'last_touch' | 'assisted';
export type AttributionEventType = 'click' | 'signup' | 'activation' | 'demo_requested' | 'trial_started' | 'purchase';
export interface ProductDNA {id:string;productName:string;url:string;description:string;audience:string[];pains:string[];differentiators:string[];competitors:string[];proof:string[];voice:string[];prohibitedClaims:string[];primaryCta:string;updatedAt:string;}
export interface GrowthOpportunity {id:string;channel:'x'|'reddit';author:string;text:string;url:string;intentScore:number;fitScore:number;riskScore:number;totalScore:number;rationale:string;suggestedReply:string;status:'new'|'approved'|'replied'|'skipped';discoveredAt:string;}
export interface AttributionEvent {id:string;type:AttributionEventType;anonymousId?:string;userId?:string;campaignId?:string;contentId?:string;angleId?:string;source?:string;value?:number;currency?:string;occurredAt:string;}
export interface AttributionCredit {conversionEventId:string;conversionType:Exclude<AttributionEventType,'click'>;campaignId?:string;contentId?:string;source?:string;weight:number;revenue:number;}
export interface GrowthMemoryFact {id:string;statement:string;confidence:number;sampleSize:number;evidence:string[];scope:'channel'|'angle'|'audience'|'cta'|'timing';}
export function opportunityScore(intent:number,fit:number,risk:number):number{return Math.round(Math.max(0,Math.min(100,intent*.46+fit*.44+(100-risk)*.10)));}
export function budgetRecommendation(input:{current:number;cpa:number;targetCpa:number;conversions:number;maxDailyIncreasePct?:number}):number{const maxIncrease=input.maxDailyIncreasePct??20;if(input.conversions<5)return input.current;if(input.cpa<=input.targetCpa*.8)return Math.round(input.current*(1+maxIncrease/100));if(input.cpa>input.targetCpa*1.2)return Math.max(1,Math.round(input.current*.85));return input.current;}
const when=(event:AttributionEvent)=>{const v=Date.parse(event.occurredAt);return Number.isFinite(v)?v:0};
const identity=(event:AttributionEvent)=>event.userId?`user:${event.userId}`:event.anonymousId?`anon:${event.anonymousId}`:null;
const direct=(event:AttributionEvent):AttributionCredit[]=>!event.campaignId&&!event.contentId&&!event.source?[]:[{conversionEventId:event.id,conversionType:event.type as AttributionCredit['conversionType'],campaignId:event.campaignId,contentId:event.contentId,source:event.source,weight:1,revenue:event.type==='purchase'?(event.value??0):0}];
export function calculateAttribution(events:AttributionEvent[],model:AttributionModel):AttributionCredit[]{const ordered=[...events].sort((a,b)=>when(a)-when(b));const credits:AttributionCredit[]=[];for(const conversion of ordered.filter(e=>e.type!=='click')){if(model==='direct'){credits.push(...direct(conversion));continue}const who=identity(conversion);if(!who){credits.push(...direct(conversion));continue}const touches=ordered.filter(e=>e.type==='click'&&identity(e)===who&&when(e)<=when(conversion)&&Boolean(e.campaignId||e.contentId||e.source));if(!touches.length){credits.push(...direct(conversion));continue}const selected=model==='first_touch'?[touches[0]]:model==='last_touch'?[touches[touches.length-1]]:touches;const weight=1/selected.length;const revenue=conversion.type==='purchase'?(conversion.value??0):0;for(const touch of selected)credits.push({conversionEventId:conversion.id,conversionType:conversion.type as AttributionCredit['conversionType'],campaignId:touch.campaignId,contentId:touch.contentId,source:touch.source,weight,revenue:revenue*weight});}return credits;}
export function summarizeAttribution(events:AttributionEvent[]){const clicks=events.filter(e=>e.type==='click').length;const signups=events.filter(e=>e.type==='signup').length;const purchases=events.filter(e=>e.type==='purchase');return{clicks,signups,activations:events.filter(e=>e.type==='activation').length,demoRequests:events.filter(e=>e.type==='demo_requested').length,trials:events.filter(e=>e.type==='trial_started').length,purchases:purchases.length,revenue:purchases.reduce((s,e)=>s+(e.value??0),0),conversionRate:clicks===0?0:Number(((signups/clicks)*100).toFixed(2))};}
