const esc=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]??char));

function shell(title:string,workspaceName:string,content:string){
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AtlasOS · ${esc(title)}</title><link rel="stylesheet" href="/assets/atlas.css"></head><body><div class="shell"><aside><div class="brand"><span>A</span><div><b>AtlasOS</b><small>${esc(workspaceName)}</small></div></div><nav><a class="nav-item" href="/app/today">Today</a><a class="nav-item" href="/app/tasks">Tasks</a><a class="nav-item ${title==="Approvals"?"active":""}" href="/app/approvals">Approvals</a><a class="nav-item ${title==="Agents"?"active":""}" href="/app/agents">Agents</a><a class="nav-item ${title==="Workflows"?"active":""}" href="/app/workflows">Workflows</a><a class="nav-item" href="/app/integrations">Integrations</a><a class="nav-item" href="/app/settings">Settings</a></nav><form method="post" action="/logout" class="logout"><button>Log out</button></form></aside><main><header><div><small class="eyebrow">CONNECTED / OPERATIONS</small><h1>${esc(title)}</h1><p>Durable, workspace-scoped operating state.</p></div></header>${content}</main></div></body></html>`;
}

export function renderAgentsPage(input:{workspaceName:string;agents:any[];canManage:boolean}){
  const rows=input.agents.length?input.agents.map(agent=>`<tr><td><b>${esc(agent.name)}</b><small>${esc(agent.description)}</small></td><td>${esc(agent.moduleId)}</td><td>${agent.enabled?'<span class="status good">Enabled</span>':'<span class="status muted">Disabled</span>'}</td><td>${esc((agent.tools??[]).join(", ")||"—")}</td><td>${esc((agent.scopes??[]).join(", ")||"—")}</td><td>$${Number(agent.costBudgetDaily??0).toFixed(2)}/day</td><td>${esc(agent.modelPreference??"Default")}</td><td>${input.canManage?`<form method="post" action="/app/agents/${encodeURIComponent(agent.id)}/toggle"><input type="hidden" name="enabled" value="${agent.enabled?"false":"true"}"><button>${agent.enabled?"Disable":"Enable"}</button></form>`:"Read only"}</td></tr>`).join(""):'<tr><td colspan="8">No agents are enabled for this workspace yet.</td></tr>';
  return shell("Agents",input.workspaceName,`<section class="panel ops"><div class="panel-head"><h2>Agent registry</h2><span>${input.agents.length} agents</span></div><div class="table-wrap"><table><thead><tr><th>Agent</th><th>Module</th><th>Status</th><th>Tools</th><th>Scopes</th><th>Budget</th><th>Model</th><th>Control</th></tr></thead><tbody>${rows}</tbody></table></div></section>`);
}

export function renderApprovalsPage(input:{workspaceName:string;approvals:any[]}){
  const cards=input.approvals.length?input.approvals.map(item=>`<article class="approval-card"><div class="approval-main"><small class="eyebrow">${esc(String(item.risk??"unknown").toUpperCase())} RISK</small><h2>${esc(item.action??"Approval required")}</h2><p>${esc(item.business_reason??"A governed workflow action requires a human decision.")}</p><dl><div><dt>Agent</dt><dd>${esc(item.agent_id??"Workflow")}</dd></div><div><dt>System</dt><dd>${esc(item.external_system??"Internal")}</dd></div><div><dt>Target</dt><dd>${esc(item.target??"—")}</dd></div><div><dt>Estimated cost</dt><dd>${item.estimated_cost==null?"—":"$"+Number(item.estimated_cost).toFixed(2)}</dd></div><div><dt>Workflow run</dt><dd>${esc(item.workflow_run_id??"—")}</dd></div><div><dt>Step</dt><dd>${esc(item.workflow_step_id??"—")}</dd></div></dl></div><div class="approval-actions"><form method="post" action="/app/approvals/${encodeURIComponent(item.id)}/approve"><label>Decision note<textarea name="note" maxlength="500"></textarea></label><button class="approve">Approve</button></form><form method="post" action="/app/approvals/${encodeURIComponent(item.id)}/reject"><input type="hidden" name="note" value="Rejected from Approval Center"><button class="reject">Reject</button></form></div></article>`).join(""):'<div class="empty-connected"><h3>No pending approvals</h3><p>Governed actions that require a human decision will appear here.</p></div>';
  return shell("Approvals",input.workspaceName,`<section class="approval-list">${cards}</section>`);
}

export function renderWorkflowsPage(input:{workspaceName:string;definitions:any[];runs:any[]}){
  const names=new Map(input.definitions.map(row=>[row.id,row]));
  const rows=input.runs.length?input.runs.map(run=>{const definition=names.get(run.workflowId);return `<tr><td><b>${esc(definition?.name??run.workflowId)}</b><small>${esc(definition?.trigger_type??"unknown")}</small></td><td><span class="status ${run.status==="completed"?"good":run.status==="waiting_approval"?"warn":run.status==="failed"||run.status==="dead_letter"?"bad":"muted"}">${esc(run.status)}</span></td><td>${String(run.currentStepIndex)}</td><td>${esc(run.initiatedBy)}</td><td>${run.startedAt?esc(new Date(run.startedAt).toLocaleString()):"—"}</td><td>${run.finishedAt?esc(new Date(run.finishedAt).toLocaleString()):"—"}</td><td>${String(run.attemptCount)}</td><td>${esc(run.lastError??"—")}</td></tr>`}).join(""):'<tr><td colspan="8">No workflow runs yet.</td></tr>';
  return shell("Workflows",input.workspaceName,`<section class="panel ops"><div class="panel-head"><h2>Execution history</h2><span>${input.runs.length} runs</span></div><div class="table-wrap"><table><thead><tr><th>Workflow</th><th>Status</th><th>Step</th><th>Initiated by</th><th>Started</th><th>Finished</th><th>Attempts</th><th>Last error</th></tr></thead><tbody>${rows}</tbody></table></div></section>`);
}
