import type {AtlasProductModel} from "@/lib/types";

function riskClass(value:string){const v=value.toLowerCase();return v.includes("critical")||v.includes("high")?"bad":v.includes("medium")||v.includes("pending")?"warn":"good"}

export function ApprovalView({model}:{model:AtlasProductModel}){
  const rows=model.rows.approvals;
  if(!rows.length)return <section className="panel"><div className="empty-state"><strong>No pending approvals.</strong>Governed actions that need human authorization will appear here. Atlas never auto-approves a risky action just to keep a workflow moving.</div></section>;
  return <section className="dashboard-grid"><article className="panel"><div className="panel-heading"><div><span className="section-kicker">APPROVAL QUEUE</span><h2>Human decisions</h2></div><small>{rows.length} pending</small></div><div className="attention-list">{rows.map(row=><div className="attention-card" key={row.id}><span className={"severity-bar "+(riskClass(row.meta)==="bad"?"critical":"warning")}/><div><h3>{row.primary}</h3><p>{row.meta}</p><footer><span>{row.secondary}</span><span>{row.status}</span></footer></div><span className="action-chip">Review</span></div>)}</div></article><article className="panel"><div className="panel-heading"><div><span className="section-kicker">GOVERNANCE</span><h2>Decision controls</h2></div></div><div className="empty-state"><strong>{model.mode==="connected"?"Connected approval authority":"Demo-only preview"}</strong>{model.mode==="connected"?"Approvals below call the existing Atlas workflow approval resolver, including workflow continuation/failure and audit logging.":"Buttons are intentionally disabled in Demo mode."}</div>{rows.slice(0,4).map(row=><div className="timeline-item" key={"decision:"+row.id}><strong>{row.primary}</strong>{model.mode==="connected"?<div style={{display:"grid",gap:6,marginTop:8}}><form method="post" action={"/api/approvals/"+encodeURIComponent(row.id)+"/approve"}><input name="note" placeholder="Optional approval note" maxLength={500} style={{width:"100%",marginBottom:6,padding:8,borderRadius:7,border:"1px solid var(--border)",background:"#080c12",color:"#fff"}}/><button className="action-chip" type="submit">Approve</button></form><form method="post" action={"/api/approvals/"+encodeURIComponent(row.id)+"/reject"}><input type="hidden" name="note" value="Rejected from AtlasOS product approval center"/><button className="action-chip" type="submit">Reject</button></form></div>:<span><b>Governed action</b><time>Demo</time></span>}</div>)}</article></section>;
}
