import type {AtlasProductModel,ProductSection} from "@/lib/types";

function metricState(state:AtlasProductModel["metrics"][number]["state"]){return state?state:""}
function statusClass(value:string){const v=value.toLowerCase();if(/critical|failed|past due|low stock|error|canceled/.test(v))return"bad";if(/warning|pending|scheduled|degraded|open/.test(v))return"warn";if(/connected|healthy|confirmed|completed|fulfilled|enabled|active|paid|ready|succeeded|value/.test(v))return"good";return""}

export function Metrics({model}:{model:AtlasProductModel}){return <section className="metrics-row">{model.metrics.map((m,i)=><article className={"metric-card "+metricState(m.state)} key={m.label+i}><span>{m.label}</span><strong>{m.value}</strong><small>{m.note}</small></article>)}</section>}

export function TodayView({model}:{model:AtlasProductModel}){return <><Metrics model={model}/><section className="dashboard-grid"><article className="panel"><div className="panel-heading"><div><span className="section-kicker">NEEDS YOUR ATTENTION</span><h2>Ranked operating priorities</h2></div><small>{model.attention.length} items</small></div>{model.attention.length?<div className="attention-list">{model.attention.slice(0,8).map(item=><div className="attention-card" key={item.id}><span className={"severity-bar "+item.severity}/><div><h3>{item.title}</h3><p>{item.why}</p><footer><span>{item.entity}</span><span>{item.status}</span></footer></div><span className="action-chip">{item.action}</span></div>)}</div>:<div className="empty-state"><strong>No open evidence-backed actions.</strong>Atlas will not manufacture issues to make this screen look busy.</div>}</article><article className="panel"><div className="panel-heading"><div><span className="section-kicker">UPCOMING</span><h2>Commitments and deadlines</h2></div><small>{model.upcoming.length}</small></div>{model.upcoming.length?<div className="timeline-list">{model.upcoming.slice(0,10).map(item=><div className="timeline-item" key={item.id}><strong>{item.title}</strong><span><b>{item.kind}</b><time>{item.when}</time></span></div>)}</div>:<div className="empty-state"><strong>No scheduled work yet.</strong>Bookings, fulfillment deadlines and tasks will appear here.</div>}</article></section><section className="lower-grid"><article className="panel"><div className="panel-heading"><div><span className="section-kicker">AI HANDLED</span><h2>Completed automated work</h2></div><small>{model.handled.length}</small></div>{model.handled.length?<div className="timeline-list">{model.handled.map(item=><div className="timeline-item" key={item.id}><strong>{item.title}</strong><span><b>{item.kind}</b><time>{item.when}</time></span></div>)}</div>:<div className="empty-state"><strong>No verified automated work yet.</strong>Only completed persisted runs are shown in Connected mode.</div>}</article><article className="panel"><div className="panel-heading"><div><span className="section-kicker">LIVE SIGNALS</span><h2>Recent business activity</h2></div><small>{model.activity.length}</small></div>{model.activity.length?<div className="timeline-list">{model.activity.slice(0,6).map(item=><div className="timeline-item" key={item.id}><strong>{item.title}</strong><span><b>{item.category}</b><time>{new Date(item.occurredAt).toLocaleString()}</time></span></div>)}</div>:<div className="empty-state"><strong>No connected activity yet.</strong>Atlas keeps empty state explicit.</div>}</article></section></>}

const descriptions:Record<ProductSection,string>={
  today:"",live:"",customers:"Relationship records scoped to this workspace.",pipeline:"Leads and opportunities, without inventing demand where the vertical does not use pipeline.",bookings:"The canonical capacity-and-time commitment model.",orders:"Price-snapshotted commerce and fulfillment state.",money:"Observed business invoices and payments. AtlasOS subscription billing is shown only in Settings.",inventory:"Operational quantity and reorder state.",work:"Human and automated operating work.",agents:"Governed agent registry.",workflows:"Durable workflow execution.",approvals:"Human decisions over risky proposed actions.",integrations:"Provider health and account state.",alerts:"Deterministic signals from persisted state.",billing:"AtlasOS subscription state and metered product usage."
};

export function SectionView({model,section}:{model:AtlasProductModel;section:ProductSection}){
  const rows=model.rows[section]||[];
  const label=section==="customers"?model.terminology.contactPlural:section==="bookings"?model.terminology.bookingPlural:section==="orders"?model.terminology.orderPlural:section==="billing"?"Billing & usage":section.charAt(0).toUpperCase()+section.slice(1);
  return <><section className="section-hero"><article className="panel section-summary"><span className="section-kicker">CANONICAL WORKSPACE STATE</span><h2>{label}</h2><p>{descriptions[section]}</p><div className="signal-strip"><div className="signal-box"><span>Records</span><strong>{rows.length}</strong></div><div className="signal-box"><span>Mode</span><strong>{model.mode}</strong></div><div className="signal-box"><span>Workspace</span><strong>{model.workspace.verticalId}</strong></div></div></article><article className="panel section-summary"><span className="section-kicker">DATA CONTRACT</span><h2>{model.mode==="connected"?"Persisted, scoped and authoritative":"Explicit fixture preview"}</h2><p>{model.mode==="connected"?"No demo records are substituted when a provider or business record is missing.":"These rows exist only to demonstrate the real application surface and are always labeled Demo."}</p></article></section><section className="table-panel"><div className="table-top"><h2>{label}</h2><small>{rows.length} record(s)</small></div>{rows.length?<div className="table-scroll"><table className="data-table"><thead><tr><th>RECORD</th><th>TYPE</th><th>STATE</th><th>DETAIL</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.primary}</strong><small>{row.id}</small></td><td>{row.secondary}</td><td><span className={"state "+statusClass(row.status)}>{row.status}</span></td><td>{row.meta}</td></tr>)}</tbody></table></div>:<div className="empty-state"><strong>No {label.toLowerCase()} data.</strong>{model.mode==="connected"?"The workspace has no persisted records for this surface.":"This vertical intentionally de-emphasizes this surface."}</div>}</section></>;
}

export function LiveFeed({model}:{model:AtlasProductModel}){return <section className="activity-grid"><article className="earth-card"><iframe className="earth-iframe" title="AtlasOS Live business observatory" src={model.mode==="connected"?"/atlas-live-earth.html?mode=connected":"/atlas-live-earth.html"} allow="fullscreen"/></article><aside className="activity-feed"><header><h2>All live signals</h2><span>● {model.mode}</span></header><div className="activity-events">{model.activity.length?model.activity.map(item=><article key={item.id} className={"activity-event "+item.category}><i/><div><strong>{item.title}</strong><p>{item.description}</p><time>{new Date(item.occurredAt).toLocaleString()} · {item.latitude!=null&&item.longitude!=null?"geographic":"non-geographic"}</time></div></article>):<div className="empty-state"><strong>No live signals.</strong>Connected mode never fills this feed with demo activity.</div>}</div></aside></section>}
