export interface QuoteInput{laborHours:number;laborRate:number;materialCost:number;materialMarkupPct:number;overheadPct:number;targetMarginPct:number;}
export interface GenericLead{id:string;workspaceId:string;source:string;estimatedValue:number;status:"new"|"qualified"|"quoted"|"won"|"lost";createdAt:string;}
export interface GenericInvoice{id:string;workspaceId:string;amount:number;status:string;dueDate:string;}
export interface GenericPayment{id:string;workspaceId:string;invoiceId:string;amount:number;paidAt:string;}
export interface ResourceCapacity{capacityHours:number;billableHours:number;laborCost:number;}
export const round2=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
export function quotePricing(input:QuoteInput){const labor=input.laborHours*input.laborRate;const materials=input.materialCost*(1+input.materialMarkupPct/100);const direct=labor+materials;const withOverhead=direct*(1+input.overheadPct/100);const margin=Math.min(Math.max(input.targetMarginPct,0),95)/100;const quoted=withOverhead/(1-margin);return{labor:round2(labor),materials:round2(materials),directCost:round2(direct),overheadAdjustedCost:round2(withOverhead),quotedTotal:round2(quoted),grossProfit:round2(quoted-direct),grossMarginPct:quoted?round2((quoted-direct)/quoted*100):0};}
export function funnelMetrics(leads:GenericLead[]){const quoted=leads.filter(x=>["quoted","won","lost"].includes(x.status)).length;const won=leads.filter(x=>x.status==="won").length;return{total:leads.length,quoted,won,lost:leads.filter(x=>x.status==="lost").length,closeRatePct:quoted?round2(won/quoted*100):0,pipelineValue:round2(leads.filter(x=>!["won","lost"].includes(x.status)).reduce((s,x)=>s+x.estimatedValue,0)),wonValue:round2(leads.filter(x=>x.status==="won").reduce((s,x)=>s+x.estimatedValue,0))};}
export function cashFlow(invoices:GenericInvoice[],payments:GenericPayment[],asOf=new Date()){const invoiced=invoices.reduce((s,x)=>s+x.amount,0),collected=payments.reduce((s,x)=>s+x.amount,0);const overdue=invoices.filter(i=>i.status!=="paid"&&new Date(i.dueDate)<asOf).reduce((s,x)=>s+x.amount,0);return{invoiced:round2(invoiced),collected:round2(collected),accountsReceivable:round2(Math.max(0,invoiced-collected)),overdue:round2(overdue),collectionRatePct:invoiced?round2(collected/invoiced*100):0};}
export function resourceUtilization(resource:ResourceCapacity){return{capacity:resource.capacityHours,billable:resource.billableHours,utilizationPct:resource.capacityHours?round2(resource.billableHours/resource.capacityHours*100):0,laborCost:round2(resource.laborCost)};}
export function businessHealth(input:{grossMarginPct:number;closeRatePct:number;collectionRatePct:number;resourceUtilizationPct:number;rating:number}){const scores=[Math.min(input.grossMarginPct/40*100,100),Math.min(input.closeRatePct/60*100,100),input.collectionRatePct,Math.min(input.resourceUtilizationPct/80*100,100),Math.min(input.rating/4.8*100,100)];return round2(scores.reduce((a,b)=>a+b,0)/scores.length);}
